### ISSUE TITLE
Android keyboard key "Done" does nothing

### ISSUE THREAD

**Issue by nixpunk** [CDargis/Roto-Cal#4]
Behavior can be seen in  add event screen.  Typically "Done" would exit keyboard entry mode.  Perhaps we can implement a "Next" that would traverse to next field.

**Comment by nixpunk** [comment]
Looks like this is a confirmed bug:

https://bugs.kde.org/show_bug.cgi?id=306892

**Comment by nixpunk** [comment]
This is still an active bug assigned to BogDan Vatra himself (confirmed above).  Nothing we will be able to do with this at the current time.

**Comment by CDargis** [comment]
Close in commit # 3083a930506ccbf74dcf85edaf66e7bcc380ea90
